aws:
  access-key: test
  secret-key: testAccessKey
  region: local
  endpoint: http://localhost:8000

hazelcast:
  cluster-name: distributed-hazel-cast-cluster
  caches:
    -
      name: music-cahce
      ttl: 5000
      records-in-memory: 200
    -
      name: alubms-cahce
      ttl: 5000
      records-in-memory: 200